### ISSUE TITLE
Do we need to replace stsdas.toolbox.convfile

### ISSUE THREAD

**Issue by justincely** [spacetelescope/iraf_replacement#46]
This package only has 3 tasks, which all do file conversions between sun and vax systems.  Since we don't use sun or vax systems anymore, this seems like an easy one to drop with little/no consequences.

- sun2vax
- tconvert
- vax2sun

@stsci-hack, can you weigh in on this - or recommend anyone I should ping?

**Comment by stsci-hack** [comment]
These can be dropped, and if a need arises later, we can implement something at that time.

**Comment by justincely** [comment]
excellent: dropped and closed until (if) we know of a need.
